config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  get "plants/:id/addplant", to: "plants#addplant", as: "addplant"
  post "plants/:id/addplant", to: "plants#planttolist", as: "updateplantlist"
  root 'welcome#index'
  get "lists/userlists", to: "lists#userlists"
  resources :plants
  resources :lists
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
    has_and_belongs_to_many :lists
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @list = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    @list.save
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end

  def userlists
  end

  def addplant
  end

  private
  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :user_id, :plant_id)
  end
  
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy, :addplant]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.order(:common_name).all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def addplant
    @user = current_user
  end

  def planttolist
    render json: @plant.list_ids
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:common_name, :sc_name, :img_url, :info, :list_ids => [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul id= "link-nav">
          <li id= "web-title">Plantabase</li>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to "List Index", lists_path %></li>
          <li><%= link_to 'Plant Index', plants_path %></li>
        </ul>
        <ul id= "login-nav">
        <% if current_user %>
          <li><%= link_to 'My Lists', lists_userlists_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
        </ul>
      </nav>
    </header>
    <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer>
      <p id= "copyright">&copy; Amber Emeny 2019</p>
    </footer>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>All Lists</h1>
<% @list.each do |data| %>
    <p class= "list-index">
        List Name: <%= data.name %><br>
        Author: <%= data.user.email %><br>
        <%= link_to 'Show List', data %>
    </p>
<% end %>

app/views/lists/new.html.erb
<h1>List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', :back %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<ul>
    <% @list.plants.each do |plant| %>
        <li><%= plant.common_name %> <%= link_to 'Show Plant Info', plant %></li>
    <% end %>
</ul>
<p><%= link_to 'Back', :back %></p>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/lists/userlists.html.erb
<h1>My Lists</h1>

<% current_user.lists.each do |data| %>
    <p class= "list-user">
        List Name: <%= data.name %><br>
        <%= link_to 'Show List', data %>
    </p>
<% end %>

app/views/plants/_form.html.erb
<%= form_with(model: plant, local: true) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field singleline">
    <%= form.label :common_name, "Common Name:" %>
    <%= form.text_field :common_name %>
  </div>

  <div class="field singleline">
    <%= form.label :sc_name, "Scientific Name:" %>
    <%= form.text_field :sc_name %>
  </div>

  <div class="field singleline">
    <%= form.label :img_url, "Image URL:" %>
    <%= form.text_field :img_url %>
  </div>

  <div class="field multiline">
    <%= form.label :info, "Plant Information:" %>
    <%= form.text_area :info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/addplant.html.erb
<h2>What List?</h2>

<% if @user.lists.empty? == false %>
    <%= form_with(model: @plant, local: true) do |form| %>
        <%= form.collection_select(:list_ids, List.all, :id, :name, {}, { multiple: true }) %>
        <%= form.submit %>
    <% end %>
<% else %>
    <h2>You have no lists!</h2>
<% end %>

app/views/plants/edit.html.erb
<div class= "plant-form">
    <h1 class= "form-title">Editing <%= @plant.common_name %></h1>
    <%= render 'form', plant: @plant %>
</div>

<div id= "main-nav-links">
    <%= link_to 'Show', @plant %>
    <%= link_to 'Back', plants_path %>
</div>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="heading-div">
  <h1 id= "plant-title">Plant Database</h1>
  <%= link_to "<button>Add a Plant</button>".html_safe , new_plant_path, class: "new-plant-link" %>
</div>

<div id="index-table-div">
  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Scientific Name</th>
        <th colspan="5"></th>
      </tr>
    </thead>

    <tbody>
      <% @plants.each do |plant| %>
        <tr>
          <td id="plant-image-column"><%= plant.img_url ? image_tag(plant.img_url, width: 150) : "" %></td>
          <td id="plant-name-column"><%= plant.common_name %></td>
          <td id= "plant-sc-name-column"><%= plant.sc_name %></td>
          <td id= "plant-details-column"><%= link_to 'Details', plant %></td>
          <%# <td><%= link_to 'Edit', edit_plant_path(plant) %>
          <%# <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' }</%#> %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/plants/new.html.erb
<div class="plant-form">
    <h1 class= "form-title">New Plant</h1>
    <%= render 'form', plant: @plant %>
</div>

<div id="main-nav-links">
<%= link_to 'Back', plants_path %>
</div>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<div id= show-content>
  <div id= "plant-show-heading">
    <div id= "plant-heading-titles">
      <h1><%= @plant.common_name %></h1>
      <i><%= @plant.sc_name %></i>
    </div>
    <div id="plant-heading-links">
      <%= link_to "<button>Add Plant to List</button>".html_safe, addplant_path(@plant) %>
      <%= link_to "<button>Edit</button>".html_safe, edit_plant_path(@plant) %>
    </div>
  </div>

  <div id= "plant-details-div">
    <div id= "plant-show-img-div">
      <%= @plant.img_url ? image_tag(@plant.img_url) : "" %>
    </div>
    <p id= "info-div">
      <%= @plant.info %>
    </p>
  </div>
</div>

app/views/welcome/index.html.erb
<h1 class= "page-title">Welcome to Plantabase!</h1>
<p class= "welcome-div">
    Thankyou for visiting this website! Plantabase is a free plant database aimed at providing a service for houseplant enthusiasts like yourself, to keep track of plants you own and the ones you want. 
</p>
<p class= "welcome-div">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing tristique risus nec feugiat in. Integer enim neque volutpat ac tincidunt vitae. Tempus iaculis urna id volutpat lacus laoreet. Eu consequat ac felis donec et. Arcu non odio euismod lacinia at quis risus sed. Euismod lacinia at quis risus sed vulputate. Nulla aliquet porttitor lacus luctus accumsan. Quis imperdiet massa tincidunt nunc pulvinar. Arcu felis bibendum ut tristique et egestas. Ornare quam viverra orci sagittis. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Consectetur adipiscing elit pellentesque habitant morbi tristique. Massa placerat duis ultricies lacus. At in tellus integer feugiat scelerisque varius morbi enim.

Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Commodo elit at imperdiet dui accumsan sit amet. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Ac tortor dignissim convallis aenean et tortor at. Porttitor lacus luctus accumsan tortor. Ac odio tempor orci dapibus ultrices. Vulputate enim nulla aliquet porttitor. Enim neque volutpat ac tincidunt. Fermentum leo vel orci porta. Convallis convallis tellus id interdum velit laoreet id. Eleifend donec pretium vulputate sapien nec sagittis. Id venenatis a condimentum vitae.

Donec pretium vulputate sapien nec sagittis aliquam malesuada. Est velit egestas dui id ornare arcu odio. Iaculis nunc sed augue lacus viverra vitae. Eu consequat ac felis donec et odio. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Donec et odio pellentesque diam volutpat. Ut porttitor leo a diam sollicitudin tempor. Id ornare arcu odio ut sem nulla. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Sit amet purus gravida quis. Velit egestas dui id ornare arcu odio ut sem nulla.

Ut porttitor leo a diam sollicitudin tempor id eu. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Porttitor eget dolor morbi non arcu risus quis varius quam. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Semper eget duis at tellus at urna condimentum mattis. Convallis posuere morbi leo urna molestie at. Tincidunt eget nullam non nisi est sit. Augue interdum velit euismod in pellentesque massa. Donec massa sapien faucibus et. Vestibulum rhoncus est pellentesque elit. Placerat orci nulla pellentesque dignissim. Cursus sit amet dictum sit amet justo donec. Dui sapien eget mi proin sed. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec.

Volutpat sed cras ornare arcu dui vivamus arcu. Eget sit amet tellus cras adipiscing enim eu. Aliquet nibh praesent tristique magna sit. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. A erat nam at lectus urna duis. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Aliquet nec ullamcorper sit amet risus nullam eget felis. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vestibulum lorem sed risus ultricies tristique. Et odio pellentesque diam volutpat. Nisl suscipit adipiscing bibendum est ultricies integer. Massa sed elementum tempus egestas sed sed risus pretium. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Nec ultrices dui sapien eget mi proin sed.

Accumsan in nisl nisi scelerisque. Pellentesque dignissim enim sit amet. A iaculis at erat pellentesque adipiscing. Bibendum neque egestas congue quisque egestas diam. Egestas diam in arcu cursus euismod quis viverra. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Sit amet risus nullam eget. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Elementum sagittis vitae et leo duis ut diam. Ornare arcu odio ut sem nulla pharetra diam sit amet. Id diam maecenas ultricies mi eget. Fames ac turpis egestas sed tempus urna et pharetra pharetra. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor elit. Tincidunt vitae semper quis lectus.

Vitae auctor eu augue ut lectus arcu bibendum at varius. Duis at tellus at urna. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. A diam maecenas sed enim ut sem viverra. Dolor sed viverra ipsum nunc aliquet. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Amet nisl purus in mollis nunc. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Eget nulla facilisi etiam dignissim diam quis enim. Metus vulputate eu scelerisque felis imperdiet. Nunc lobortis mattis aliquam faucibus purus in. Morbi tristique senectus et netus.

Pellentesque sit amet porttitor eget dolor morbi non arcu. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Id porta nibh venenatis cras sed felis eget velit. Porta nibh venenatis cras sed felis eget velit aliquet. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Suspendisse sed nisi lacus sed viverra. Lorem ipsum dolor sit amet. Neque sodales ut etiam sit amet nisl. Lobortis elementum nibh tellus molestie nunc non blandit. Massa sed elementum tempus egestas. Rutrum quisque non tellus orci. Donec ac odio tempor orci dapibus ultrices. Vel pretium lectus quam id leo in vitae turpis massa. Porttitor massa id neque aliquam.

Sed blandit libero volutpat sed cras ornare arcu. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Consequat semper viverra nam libero justo laoreet. Quis risus sed vulputate odio ut enim blandit. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Eu feugiat pretium nibh ipsum consequat nisl. Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Sed vulputate odio ut enim blandit volutpat. Elementum tempus egestas sed sed risus pretium quam vulputate dignissim. Ipsum a arcu cursus vitae congue. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Penatibus et magnis dis parturient montes nascetur. Volutpat ac tincidunt vitae semper quis lectus nulla at. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Mi proin sed libero enim sed faucibus turpis in eu. Eget nulla facilisi etiam dignissim. Sagittis nisl rhoncus mattis rhoncus urna neque. In mollis nunc sed id. Cras semper auctor neque vitae tempus quam pellentesque nec nam.

Senectus et netus et malesuada fames. Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Vulputate mi sit amet mauris. Purus ut faucibus pulvinar elementum integer. Morbi non arcu risus quis varius quam. Pretium quam vulputate dignissim suspendisse in. Tortor at risus viverra adipiscing at in tellus integer feugiat. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Elementum integer enim neque volutpat ac. Dictum varius duis at consectetur lorem donec. Pellentesque elit ullamcorper dignissim cras. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. A arcu cursus vitae congue. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Scelerisque in dictum non consectetur a erat nam at lectus.
</p>